# This is a basic workflow to help you get started with Actions

name: Build and push the latest build to staging

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_push_image:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v1
      - name: Docker Login
  # You may pin to the exact commit or the version.
  # uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        uses: docker/login-action@v1.10.0
        with:
          registry: ${{ secrets.ACR_NAME }}
          username: ${{ secrets.ACR_LOGIN }}
          password: ${{ secrets.ACR_PASSWORD }}     

      - name: Build and push staging images
  # You may pin to the exact commit or the version.
  # uses: docker/build-push-action@1bc1040caef9e604eb543693ba89b5bf4fc80935
        uses: docker/build-push-action@v2.6.1
        with:
          context: .
          tags: ${{secrets.ACR_NAME}}/contoso-website:latest
          push: true
  deploy:
   runs-on: ubuntu-latest
   needs: build_push_image
   steps: 
   
   - uses: actions/checkout@v2
   
   - name: Helm tool installer
  uses: Azure/setup-helm@v1
  with:
    # Version of helm
    version: v3.3.1
    # Github token
    token: # default is ${{ github.token }}
    
    - name: Azure Kubernetes set context
  uses: Azure/aks-set-context@v1.1
  with:
    # Azure credentials i.e. output of `az ad sp create-for-rbac --sdk-auth`
    creds: ${{ secrets.AZURE_CREDENTIALS }}
    # Resource Group Name
    resource-group: mslearn-gh-pipelines-30518 
    # AKS Cluster Name
    cluster-name: contoso-video
   
   
   

